### ISSUE TITLE
Can't Read EAN-13 barcodes with Leading Zero

### ISSUE THREAD

**Issue by Bhanuka-BizSmarTech** [mebjas/html5-qrcode#361]
Examples:
![barcode (4)](https://user-images.githubusercontent.com/84697345/145342385-f4f7aa38-5a38-4499-ad98-3964cf190ec2.gif)
![barcode (5)](https://user-images.githubusercontent.com/84697345/145342533-ff4fbf12-5422-48e6-afc6-0cc2d05a0cbf.gif)

**Comment by mebjas** [comment]
I tried with some other online barcode readers as well and all of them seem to ignore the leading 0. 

I generated one online and it seemed to show the same behavior:

![image](https://user-images.githubusercontent.com/3007365/145710858-ff42da8f-cd8b-4e04-8907-55a7efa94b72.png)

Based on some reading online it looks like an EAN-13 code with leading "0" is  a UPC-A code and it maybe ok to ignore the leading 0. If your business logic really requires the accurate full value, you could add a logic to prepend a 0 if the length of the decodedText < 13.

One hack could be to prepend a  "0" in cases where 12 digits are not observed for EAN13 code.

**Comment by jp06** [comment]
Maybe related to https://github.com/zxing-js/library/issues/457? According to a [comment](https://github.com/zxing-js/library/pull/456#issuecomment-951591567) in the unmerged PR, it should be fixed by now. Maybe just need to update the zxing dependency.

**Comment by mebjas** [comment]
This now needs to be back-ported to https://github.com/mebjas/html5-qrcode/blob/master/third_party/zxing-js.umd.js considering zxing-js is no longer well maintained and `html5-qrcode` has modified internal version further. 

A better refactor would be if we maintain a separate version (fork) of original zxing-js library so it's easier to port.

**Comment by dalito** [comment]
Out of curiosity I tried to scan the three EAN-13-barcodes above. All were correctly recognized using version 2.1.6.

I am writing the value to a string input and the leading zero is shown there. Maybe the leading zero got lost when converting to a number?

**Comment by Modjo69** [comment]
> 

Hello, i would like to know what type of phone are you using ? Because for me the three example above still doesn't work on 2.1.6

**Comment by Modjo69** [comment]
> Out of curiosity I tried to scan the three EAN-13-barcodes above. All were correctly recognized using version 2.1.6.
> 
> I am writing the value to a string input and the leading zero is shown there. Maybe the leading zero got lost when converting to a number?

Hello, i would like to know what type of phone are you using ? Because for me the three example above still doesn't work on 2.1.6

**Comment by dalito** [comment]
When I try to read above barcodes with https://scanapp.org I also cannot see the leading zeros. 

However, in my code that uses version 2.1.6 and reads `decodedText` the leading zeros are present. So I do not believe that it has much to do with the phone. I used a Huawei P30 Pro with the current version of Chrome (96.0.4664.104).

**Comment by mebjas** [comment]
Scanapp uses experimental support of using `BarcodeDetector` API which uses the hardware supported detectors first before zxing - so it could be because of that.

```js

	let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader", 
        { 
            fps: 10,
            qrbox: qrboxFunction,
            // Important notice: this is experimental feature, use it at your
            // own risk. See documentation in
            // mebjas@/html5-qrcode/src/experimental-features.ts
            experimentalFeatures: {
                useBarCodeDetectorIfSupported: true
            },
            rememberLastUsedCamera: true,
            aspectRatio: 1.7777778
        });

```

Can you try adding this info

```js
    experimentalFeatures: {
       useBarCodeDetectorIfSupported: true
    },
```

**Comment by dalito** [comment]
I am not sure I understand what to try: Do you mean to 
```
experimentalFeatures: {
       useBarCodeDetectorIfSupported: true
    },
```
to my app/code and see if it "looses" the leading zeros?

**Comment by dalito** [comment]
With `useBarCodeDetectorIfSupported: true` the barcodes above are not read/detected but with `useBarCodeDetectorIfSupported: flase` they are correctly read. I used version 2.1.6 for this test.
